### ISSUE TITLE
Проверка регистрации пользователей, e-mail, соцсети

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#103]
[14.01.2015 9:09:24] Tamaranga Анжелика: настройка регистрации через соц. сети описана в файле faq.txt - она работает и доделана

1. Проверить работу почтовой системы (при регистрации  обычным способом с вводом е-мейла ничего не приходит на почту)

2. проверить регистрацию через соц.сети

**Comment by vkucha** [comment]
по емейл работает, если не отправляеться нужно посмотреть есть ли шаблон для отправки письма
