### ISSUE TITLE
Страница Компании - доработка

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#110]
http://legator.by/user/eruditeby/

Сделать главной Портфолио,
попросить павла заполнить нужной недостающей информацией,

привести к такому виду http://legator.by/user/maintest/portfolio/  

+++ полоса с сотрудниками

все что нужно выровнять.

**Comment by warks89** [comment]
http://loc.legator.by/user/delawyersbiz/portfolio/ - исправить верстку
