### ISSUE TITLE
Не выводит Информацию у фирм (поле "Резюме" в Админке)

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#111]
![default](https://cloud.githubusercontent.com/assets/10129275/5772702/ce81cf2c-9d67-11e4-81e4-d523427c8bb9.png)
http://legator.by/user/eruditeby/info/

**Comment by vkucha** [comment]
нужна проверка

**Comment by coolkabro** [comment]
пусто

**Comment by warks89** [comment]
вывод текста работает, если ничего не видно то ctrl+f5
