### ISSUE TITLE
Компания>портфолио>добавить работу (при нажатии выдаёт ошибку).

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#112]
![default](https://cloud.githubusercontent.com/assets/10129275/5772730/55ffbf36-9d68-11e4-8ad9-6ac3f2c8777a.png)
выкидывает сюда:
![default](https://cloud.githubusercontent.com/assets/10129275/5772733/6ead076e-9d68-11e4-8c93-4b6893c1829b.png)

**Comment by vkucha** [comment]
исправлено
