### ISSUE TITLE
Карта не отображается

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#119]
Есть:
![image](https://cloud.githubusercontent.com/assets/10115629/5800714/5e074c52-9ff3-11e4-8d31-05055e01a1d1.png)

Должно быть:

![image](https://cloud.githubusercontent.com/assets/10115629/5800707/49be360c-9ff3-11e4-9c88-096adbd2f3ad.png)

**Comment by vkucha** [comment]
исправлено
