### ISSUE TITLE
Корректировка верстки страницы Фирмы, Бюро

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#124]
![image](https://cloud.githubusercontent.com/assets/10115629/5832930/71b56e4e-a15d-11e4-9f7e-7dc2f1faae2f.png)

![image](https://cloud.githubusercontent.com/assets/10115629/5832963/1da5e2a6-a15e-11e4-9310-4d3629fbb158.png)

![image](https://cloud.githubusercontent.com/assets/10115629/5832974/3f98f420-a15e-11e4-9eac-254caee99b63.png)

Откуда взята идея:

http://www.dom.by/list/laminat/minsk/

Логотипы разные, в рамке смотрятся неплохо.

**Comment by vkucha** [comment]
зделано
