### ISSUE TITLE
Добавление специализаций в личном кабинете пользователя - в настройках

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#129]
Личный кабинет пользователя (адвоката)
http://legator.by/user/settings
Данные для входа:
test@mail.ru    test

Настройки - Внизу по странице - Специализации и навыки, нужно сделать выбор их как в админке, для простоты....
![image](https://cloud.githubusercontent.com/assets/10115629/5855651/b7f53972-a24b-11e4-8f6d-11147aab841b.png)

Проверить чтобы сохранялись данные...

На этой же странице ( если смог понять где была ошибка) - не выводиться тоже карта.

**Comment by vkucha** [comment]
спецеализации зделаны
