### ISSUE TITLE
Вылетает фатал ерор при нажатии на "Информация"

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#131]
![default](https://cloud.githubusercontent.com/assets/10129275/5875638/7f5e6d42-a320-11e4-9a7d-94c9da700eb5.png)

**Comment by coolkabro** [comment]
![default](https://cloud.githubusercontent.com/assets/10129275/5875650/ab863bb6-a320-11e4-94a8-b572c7f3acc2.png)

**Comment by vkucha** [comment]
там все нормально
