### ISSUE TITLE
Работа со спецразмещениями

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#139]
![image](https://cloud.githubusercontent.com/assets/10115629/5918079/8f37949c-a635-11e4-90c4-d0a089f807c8.png)
 

Важно: есть общая страница Каталога (главная) http://legator.by/users/
             Есть специализации в каталоге http://legator.by/users/alimenty/isk-na-alimenty

Должна быть возможность выкупать места на главной странице каталога, и на каждой метке

Отдельно: !!!!!!!!!!!!!

Для услуг: тут стандартные возможности системы: закрепление (фиксация вверху

Точно также для каждого раздела меню.

**Comment by coolkabro** [comment]
Добавить возможность добавления "ПРО" аккаунта, удаление "ПРО" аккаунта из админки.
