### ISSUE TITLE
Страница адвоката - специализации - позвони обсудим когда займешься правкой

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#141]
На основной странице не более 3 строчек специализаций
![image](https://cloud.githubusercontent.com/assets/10115629/5934149/23ea7338-a6dc-11e4-92b9-172a8ecfcc70.png)
При клике "все специализации" - разворачивается область
![image](https://cloud.githubusercontent.com/assets/10115629/5934059/b74be74e-a6da-11e4-98ac-226b54e373ab.png)

дерево я взял как из админки, в этом дереве указаны все специализации которые выбрал адвокат или фирма.

**Comment by vkucha** [comment]
зделано
