### ISSUE TITLE
Общий каталог исполнителей - отображение фирмы

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#154]
![image](https://cloud.githubusercontent.com/assets/10115629/5953354/8a1991f8-a799-11e4-9c69-f50d040372be.png)

Проблема:
![image](https://cloud.githubusercontent.com/assets/10115629/5953357/9bd56606-a799-11e4-8ce3-d19911bb10d9.png)

**Comment by warks89** [comment]
Сначала нужно разобраться с загрузкой логотипов.  Сейчас все аватарки обрезаются

**Comment by paramaxstudio** [comment]
Получится ли так:

Проверка на то, что этот юзер - компания,

и тогда лого подгружать как есть, только ограничение css задать.

это ведь уже работает на странице компании http://legator.by/user/legator116/portfolio/
