### ISSUE TITLE
Ошибка с переключением страниц (всё внутри).

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#159]
тырк в общем списке "Каталог юристов и адвокатов"
![1](https://cloud.githubusercontent.com/assets/10129275/5972286/e056b6b2-a867-11e4-858c-c5dcf82f1c98.png)
перекидывает на страницу с адвокатскими бюро (всё нормально)
![2](https://cloud.githubusercontent.com/assets/10129275/5972293/f59f1eba-a867-11e4-9194-d8987233b537.png)
при переключении страницы:
![3](https://cloud.githubusercontent.com/assets/10129275/5972299/09addee6-a868-11e4-9fc0-50d20b3e6a5a.png)
выкидывает на общую по юристам и адвокатам:
![4](https://cloud.githubusercontent.com/assets/10129275/5972302/17405f5c-a868-11e4-94ac-db1a9afe174a.png)
http://legator.by/users/?tag=%D0%B0%D0%B4%D0%B2%D0%BE%D0%BA%D0%B0%D1%82%D1%81%D0%BA%D0%BE%D0%B5%20%D0%B1%D1%8E%D1%80%D0%BE-49

**Comment by vkucha** [comment]
исправил
