### ISSUE TITLE
При удалении юзера перекидывает на 1 страницу, нужно чтобы на той же странице и оставалось.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#161]
![default](https://cloud.githubusercontent.com/assets/10129275/5972553/99a23e58-a86c-11e4-9202-1cc4363325e2.png)

**Comment by coolkabro** [comment]
И желательно чтобы так было везде, не перекидывало в начало.

**Comment by vkucha** [comment]
Каждая страница настраеваться индивидуально, если еще гдето заметиш сразц открывай задачу с ссылкой на страницу
