### ISSUE TITLE
Сделать рабочую сортировку пользователей по городам в админке.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#162]
![default](https://cloud.githubusercontent.com/assets/10129275/5973064/fb272000-a874-11e4-972e-5a7795137f07.png)
Сейчас не работает нормально, ввожу минск, кидает на 1-ую страницу, и ничего не меняется, так же остаются брестчане, могилевчане и т.д.

**Comment by vkucha** [comment]
она работает просто выбирать город надо мышкой, а не кнопкой enter
