### ISSUE TITLE
Уменьшить кол-во знаков отображающихся в поиске до 150 +- и в разделе "Все услуги" до 500 +-

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#169]

**Comment by coolkabro** [comment]
http://legator.by/user/levpartby/shop/
нужно чтобы показывало не такую кучу текста, а вот так 
![default](https://cloud.githubusercontent.com/assets/10129275/6104660/850f93fe-b060-11e4-87d2-0d97b42b296b.png)

**Comment by vkucha** [comment]
зделано
