### ISSUE TITLE
Презентация коттеджи

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#171]
Прайс-табличку взять отсюда http://paramax.by

Верстку таблицы с позициями отсюда: http://flatbook.by/page/prezentaciya-portala-posytochnoi-arendni-flatbook

PSD
https://drive.google.com/file/d/0B-4yo0Upvy-BWV9OWUJzWWFqSVk/view?usp=sharing

**Comment by warks89** [comment]
http://flatbook.by/prezentaciya-portala-kattedgi-flatbook.html
