### ISSUE TITLE
Не показывает фирму в присвоеной ей специализации! (всё внутри)

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#178]
тырк сюда
![1](https://cloud.githubusercontent.com/assets/10129275/6059811/fcf18b24-ad46-11e4-8dd2-959089e9b592.png)
и этой фирмы тут нет
![2](https://cloud.githubusercontent.com/assets/10129275/6059818/04deebc4-ad47-11e4-987d-d3b5cf0bd25a.png)
http://legator.by/user/trustlawfirmby/portfolio/

**Comment by vkucha** [comment]
не показываеться потому что в админке в вкладке про у пользователя нет етой категории, пользователь появиться в течении часа
