### ISSUE TITLE
Функционал по спец. позициям.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#180]
![default](https://cloud.githubusercontent.com/assets/10129275/6060713/315db4aa-ad51-11e4-82d6-f6ce839f8baf.png)
Добавить возможность прямо с этой страницы: включать/выключать спец. позицию, редактировать дату, редактировать специализацию (поменять Корень каталога на Корпоративное право) по поиску, изменять позицию.

**Comment by coolkabro** [comment]
+ добавить поиск по емейлу 
![default](https://cloud.githubusercontent.com/assets/10129275/6060833/873fdff0-ad52-11e4-9914-e5231f26aa8e.png)

**Comment by vkucha** [comment]
все что было возможно зделать зделано
