### ISSUE TITLE
Косяк с отображением услуг/портфолио (всё внутри).

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#181]
В "корне каталога" выглядит так:
![1](https://cloud.githubusercontent.com/assets/10129275/6061411/a01fe2b2-ad58-11e4-8130-9b8f08531d30.png)
А если смотреть в разделе "Корпоративное право" выглядит вот так:
![2](https://cloud.githubusercontent.com/assets/10129275/6061419/b8dd8124-ad58-11e4-903f-eb77b3b7c08a.png)
http://legator.by/users/
http://legator.by/users/pravo/korporativnoje-pravo
нужно привести к общему виду как на главной

**Comment by coolkabro** [comment]
![default](https://cloud.githubusercontent.com/assets/10129275/6061534/a3702f66-ad59-11e4-80ec-b5143d9167a3.jpg)

**Comment by vkucha** [comment]
исправлено
