### ISSUE TITLE
Поставить основную валюту для всего сайта рубли! Формат: 1 900 000 р. (разделять пробелами)

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#190]
![default](https://cloud.githubusercontent.com/assets/10129275/6128075/04f373c8-b143-11e4-839f-ebe373c29de5.png)
рубли - р.

**Comment by coolkabro** [comment]
Изменить формат отображения ценников на всём сайте!

**Comment by vkucha** [comment]
вроде везде нужно перепроверить
