### ISSUE TITLE
!Доработка услуги заказать онлайн

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#212]
Заходит заказчик на сайт в раздел "Услуги и цены".
Выбирает нужную ему услуги и нажимает Заказать on-line!
![1](https://cloud.githubusercontent.com/assets/10129275/6164405/f69a6ad4-b2af-11e4-91ee-81982292c973.png)
Перекидывает на страницу услуги!
![2](https://cloud.githubusercontent.com/assets/10129275/6164427/27becd80-b2b0-11e4-9dcd-9f5827de0103.png)
Нужно добавить кнопку Заказать on-line!
![3](https://cloud.githubusercontent.com/assets/10129275/6164442/6125a364-b2b0-11e4-854e-825ffa926f53.png)
При нажатии на кнопку должна появляться форма типо такой:
![4](https://cloud.githubusercontent.com/assets/10129275/6164531/252639ae-b2b1-11e4-8814-b84b1dfe97fa.png)
Обозначения:
1.) В этом поле должна автоматом ставиться специализация и название, которые привязаны к услуге (исполнитель должен будет видеть по какому поводу ему пишут)
2.) В поле просто текст обращения заказчика к исполнителю (переименовать на "Сообщение исполнителю")
3.) В поле автоматом должен ставиться e-mail исполнителя услуги (самая важная часть, нужно чтобы после нажатия на завершающую кнопку "Сделать заказ"/"Отправить сообщение"
![5](https://cloud.githubusercontent.com/assets/10129275/6164694/993e58de-b2b2-11e4-9f52-3c7af521b5a1.png)
сообщение отправлялось исполнителю на почту внутри сайта и уведомление на его почту о том, что ему поступил заказ с Legator.by
4.) Условия оплаты: галочка на цена договорная и поле с указанием бюджета.

После отправки заявки на услугу исполнителю должно приходить письмо такого вида и на его емейл и на почту внутри сайта (там открывается чат между заказчиком и исполнителем, т.е. заказчика должно закинуть в этот чат):
![7](https://cloud.githubusercontent.com/assets/10129275/6166338/627b2e90-b2c0-11e4-9c21-42de9b904069.png)
Legator.by - должна быть активной ссылкой!
Специализация, услуга и ссылка на услугу должна проставляться автоматом!

**Comment by vkucha** [comment]
http://SSMaker.ru/44eb8c8a/
