### ISSUE TITLE
A Спецпозиции в каталоге

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#230]
![image](https://cloud.githubusercontent.com/assets/10115629/6243915/b6a30092-b75c-11e4-8ab7-0af5fead5aa1.png)

обвести желтым контуром - посмотреть как будет выглядеть

2 вариант: сделать только бока желтые слева и справа, если первый ваариант будет сильно мозолить глаза

**Comment by vkucha** [comment]
если нормально то закрыть задачу
