### ISSUE TITLE
Закрыть внешние ссылки в профиле от индексации

### ISSUE THREAD

**Issue by Dekap** [paramaxstudio/paramax#233]
http://gyazo.com/27fe81bd7913af738f86e880701a2576

<noindex>
<a rel="nofollow" href="http://сайт.ru/">Внешняя ссылка</a>
</noindex>
http://gyazo.com/a6cb944101c63834b4b4d0e59215e7ef

**Comment by Dekap** [comment]
ДОПОЛНЕНИЕ
закрыть возможность проставления активных внешних ссылок при редактировании или добавлении любых данных

**Comment by warks89** [comment]
в профиле закрыл

**Comment by vkucha** [comment]
проверить надо

**Comment by vkucha** [comment]
из админки ссылки не удаляютсья
