### ISSUE TITLE
А Переделать внешний вид услуг, примерно как на этом сайте! (Только в услугах, которые находятся в профиле пользователя)

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#244]
Нужно чтобы на превью показывало основную инфу, типо услуга и цена, а при нажатии на кнопку открывалась вся подробная инфа.
http://legator.by/user/maintest/uslugi/

**Comment by vkucha** [comment]
http://dviktorio.by/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8/%D0%B1%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B5-%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8
