### ISSUE TITLE
Добавить ссылки на главной страницы (переход с картинок)

### ISSUE THREAD

**Issue by warks89** [paramaxstudio/paramax#253]
Раздел имущества при разводе http://legator.by/users/razvod/razdel-imushhestva-pri-razvode
Защита прав потребителей http://legator.by/users/zashhita-prav
Взыскания алиментов http://legator.by/users/alimenty
Консультация по разводу http://legator.by/users/razvod/konsultacija-po-razvodu
Страхование http://legator.by/users/strahovanije
Жалобы http://legator.by/users/zhaloba/

**Comment by vkucha** [comment]
Возобнови задачу если бдет что то новое
