### ISSUE TITLE
(Предложение) Убрать из ЛК и админки дату рождения и пол. Без выбранной даты рождения нельзя сохранить настройки в личном кабинете на сайте.

### ISSUE THREAD

**Issue by Dimarabota** [paramaxstudio/paramax#293]
![0475ad0be129540cc0e1f2bb8d284b67](https://cloud.githubusercontent.com/assets/11388101/6616659/42dfddda-c8c1-11e4-90c9-49eb645ef499.png)
![2417f5d679f93945b0ff1ede99689652](https://cloud.githubusercontent.com/assets/11388101/6616660/42e1f7a0-c8c1-11e4-90b3-9a8f25c3430f.png)

**Comment by vkucha** [comment]
там все нормально работает
