### ISSUE TITLE
Косяк со специализациями (всё внутри)!

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#322]
У фирмы есть специализации по регистрации (выделенные):
![screenshot](https://cloud.githubusercontent.com/assets/10129275/6964560/0a58b6a6-d953-11e4-95c0-8b7d45ddb3cd.png)
Но в каталоге по этим специализациям, такой фирмы нет, скорее всего это массово как-то
![2](https://cloud.githubusercontent.com/assets/10129275/6964566/21869b0e-d953-11e4-8503-e32930088352.png)

**Comment by vkucha** [comment]
https://github.com/paramaxstudio/paramax/issues/274
