### ISSUE TITLE
Легатор, категории непонятно работают

### ISSUE THREAD

**Issue by Dimarabota** [paramaxstudio/paramax#325]
Суть в том, что при выборе некоторых категорий полный список отображается обрезанным.
![1](https://cloud.githubusercontent.com/assets/11388101/7023547/b4cf28e2-dd3e-11e4-8477-5b070f234ef3.png)
![2](https://cloud.githubusercontent.com/assets/11388101/7023548/b4cf22d4-dd3e-11e4-90c8-4e6e12aeea07.png)
![3](https://cloud.githubusercontent.com/assets/11388101/7023546/b4ce5516-dd3e-11e4-8021-c79698599344.png)

**Comment by warks89** [comment]
Возможно проблема в кешировании, на локальной версии отображается полный список

**Comment by warks89** [comment]
очистил кеш и при обновлении появился весь список
