### ISSUE TITLE
Добавить возможность добавления портфолио из админки.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#47]
![default](https://cloud.githubusercontent.com/assets/10129275/5525638/3bd10b82-89fa-11e4-8993-0504837598b6.png)
Или прямо из редактора пользователя
![2](https://cloud.githubusercontent.com/assets/10129275/5525670/9c7bcfa8-89fa-11e4-9393-73612c7590ad.png)

**Comment by vkucha** [comment]
зделано
