### ISSUE TITLE
Изменение вида добавления специализаций!

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#52]
Сейчас специализации юзеру нужно присваивать так:
![default](https://cloud.githubusercontent.com/assets/10129275/5567193/32ab3dd8-8f50-11e4-8031-b48d252b2d4c.png)
Нужно сделать примерно что-то вроде этого:
![default](https://cloud.githubusercontent.com/assets/10129275/5567210/a3e966a0-8f50-11e4-8fce-63d42b52b08a.png)
Если выбираешь главную категорию (тут это Долг), то автоматом должны выделяться все подкатегории привязаные к ней.

**Comment by vkucha** [comment]
зделано
