### ISSUE TITLE
Не нажимается кнопка "Загрузить" (фото) из профиля юзера.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#53]
![default](https://cloud.githubusercontent.com/assets/10129275/5567275/91f81dc2-8f52-11e4-9b5d-7a8ef8015d4d.png)

**Comment by warks89** [comment]
ошибка возникает из-за конфликта библиотек  на этой странице

**Comment by vkucha** [comment]
исправлено
