### ISSUE TITLE
Не добавляется емейл пользователя! (Магазин-добавление товара)

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#77]
![ecec0ea9](https://cloud.githubusercontent.com/assets/10129275/5700227/0701c016-9a4b-11e4-90d1-ba44a8532966.jpg)

**Comment by vkucha** [comment]
там просто нужно выбирать емейл не клавиатурой, а мышкой, в системе есть другое действие на нажатие кнопки ентер
