### ISSUE TITLE
Реализовать возможность добавлять пояснительный текст для каждой метки через админку

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#82]
![-1](https://cloud.githubusercontent.com/assets/10115629/5703110/09c2cf0c-9a73-11e4-9546-a67f9175a916.jpg)

Уточнение: в отдельности для дерева категорий магазина в админке и для дерева категорий каталога ( само дерево специализаций одно и то же, но описание для услуги и каталога  - разное)

В админке есть это разделение.

Если есть уже готовый встроенный редактор для текстого поля - лучше использовать.

**Comment by vkucha** [comment]
Для пользователей зделано

**Comment by vkucha** [comment]
для магазина зделано
