### ISSUE TITLE
Продублировать сео

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#83]
![image](https://cloud.githubusercontent.com/assets/10115629/5703149/9c9cb1bc-9a73-11e4-9b78-cf415b5f2e5b.png)

в админке, в разделе Магазин - Категории реализован функционал макросов ( не знаю работает он или нет)

они нужны чтобы формировать автоматическии описание Титл+еще что-то - формируется заговолок h1 например

его желательно продоублировать в работу с сео в категорих каталога Специализации - Категории,Специализации

**Comment by vkucha** [comment]
там работает макрос с названием  {site.title}
