### ISSUE TITLE
Не появляются дополнительные специализации в общем списке "Специализации" в правом столбце

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#94]
![1](https://cloud.githubusercontent.com/assets/10129275/5735366/f782aac4-9bd5-11e4-85e5-c2d3b566070e.png)

и там:

![2](https://cloud.githubusercontent.com/assets/10129275/5735416/8605e2f2-9bd6-11e4-86eb-47545f5e0f1d.png)

**Comment by vkucha** [comment]
исправлено
