### ISSUE TITLE
Вывод типовых услуг на странице адвоката (профиль)

### ISSUE THREAD

**Issue by paramaxstudio** [paramaxstudio/paramax#96]
Здесь
![image](https://cloud.githubusercontent.com/assets/10115629/5735619/d943cc92-9bd9-11e4-8fe2-19d8bf7ccb33.png)
не работает вывод услуг и ссылка все услуги

сделать как выводится уже в каталоге
![image](https://cloud.githubusercontent.com/assets/10115629/5735614/c5708502-9bd9-11e4-9664-dc382773ba68.png)

**Comment by warks89** [comment]
Выводятся сразу все, пока без категорий
