### ISSUE TITLE
Не добавляются специализация в категории.

### ISSUE THREAD

**Issue by coolkabro** [paramaxstudio/paramax#99]
Не добавляются специализации в категории. Нажимаю добавить специализацию, прописываю имя, генерирую урл, нажимаю "Включить" и сохранить. После этих действий специализация не появляется.
![default](https://cloud.githubusercontent.com/assets/10129275/5735818/889c551c-9bdd-11e4-949a-5b1cbbff6f9d.png)

**Comment by vkucha** [comment]
исправлено
